<a href="https://colab.research.google.com/github/victordotm/TFM/blob/master/Eliminar_imagenes_duplicadas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Eliminar Imágenes  Duplicadas<br>
Compara la imágenes obtenidas para cada compañia de motos en cada una de las distintas búsquedas realizadas. <br>
Detecta las imágenes idénticas y las elimina.<br>
Evitando así que el dataset contenga imágenes duplicadas.

In [0]:
BASE_FOLDER = "/content/drive/My Drive/Colab Notebooks/TFM/"
BASE_FOLDER_donwloads = BASE_FOLDER+"Dataset_donwload/"

from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
#Importamos la libreria que nos permite usar las funciones de interaccion con el directorio y ficheros
import os

#Indicamo el path base en el que trabajaremos. Donde estan nuestros Datasets
path = BASE_FOLDER_donwloads

In [0]:
#contendrá las diferentes carpetas resultado de la búsqueda de imagenes
folders = [] 

#contendrá las carpetas con imágenes de cada compañia de alquiler
folders_ecooltra = []
folders_yego = []
folders_muving = []
folders_acciona = []
folders_blinkee = []
folders_motos = []


for r, d, f in os.walk(path):
  
    for folder in d:
        folders.append(os.path.join(r, folder))
        
        if 'ecooltra' in folder:
          folders_ecooltra.append(os.path.join(r, folder))
          
        elif 'muving' in folder:
          folders_muving.append(os.path.join(r, folder))
        
        elif 'yego' in folder:
          folders_yego.append(os.path.join(r, folder))
          
        elif 'acciona' in folder:
          folders_acciona.append(os.path.join(r, folder))
        
        elif 'Blinkee' in folder:
          folders_blinkee.append(os.path.join(r, folder))
        
        else:
          folders_motos.append(os.path.join(r, folder))


In [0]:
#definimos una función para listar todas las imagenes de una misma compañia de alquiler

def listarImagenes (carpetas, listaImagenes):
  
  for numfolders in range(len(carpetas)):
  
    for r, d, f in os.walk(carpetas[numfolders]):
        for file in f:
                listaImagenes.append(os.path.join(r, file))

  for f in listaImagenes:
      print(f)
  
  return True

In [0]:
#contendrá la lista de ficheros de imágenes de cada compañia de alquiler
files_ecooltra = []
files_yego = []
files_muving = []
files_acciona = []
files_blinkee = []
files_motos = []

In [0]:
listarImagenes (folders_ecooltra, files_ecooltra)
listarImagenes (folders_yego, files_yego)
listarImagenes (folders_muving, files_muving)
listarImagenes (folders_acciona, files_acciona)
listarImagenes (folders_blinkee, files_blinkee)
listarImagenes (folders_motos, files_motos)

/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000000.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000001.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000002.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000003.png
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000004.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000005.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000006.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000007.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000008.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000009.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000010.jpeg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000011.jpg
/co

True

In [0]:
#Decorador para calcular_tiempo a la función para la cual queremos calcular el tiempo de ejecución

from time import time
#Función para calcular el tiempo de ejecución
def calcular_tiempo(f): # @calcular_tiempo
   
    def wrapper(*args, **kwargs):        
        inicio = time()       
        resultado = f(*args, **kwargs)       
        tiempo = time() - inicio
        print("Tiempo de ejecución para algoritmo: "+str(tiempo))
        return resultado
    
    return wrapper
  

In [0]:
import cv2
from google.colab.patches import cv2_imshow
import numpy as np

In [0]:
@calcular_tiempo
def BuscarImagenesDuplicadas(image_files, basefolder_path):
  num_image2write=0
  save_baseimage = True
  num_imag_dup=0
  
  for numfiles in range(len(image_files)):
    file_base = image_files[0]
    print(file_base)
    image_files.remove(file_base) #eliminamos de la lista la imágen inicial que usamos como base de comparación para evitar comparaciones duplicadas en los siguientes loops
    baseImage = cv2.imread(file_base)
    
    for numfiles2 in range(len(image_files)): 
      compareImage = cv2.imread(image_files[numfiles2])

      #¿Mismo tamaño?
      if baseImage.shape == compareImage.shape: #Comparamos si coincide el tamaño de la imagen 

        # Si coincide el tamaño verificamos si tienen los mismos canales (colores)
        difference = cv2.subtract(baseImage, compareImage)
        b, g, r = cv2.split(difference)

        if cv2.countNonZero(b) == 0 and cv2.countNonZero(g) == 0 and cv2.countNonZero(r) == 0:
          num_imag_dup = num_imag_dup + 1
          save_baseimage = False
          break; #si encontramos una igual, salimos del for

        else: #Si no coincide en canales, guardamos la imagen, puesto que no es la misma. Guardamos la imagen base que estamabos comparando
          save_baseimage = True

      #Diferente tamaño
      else: #Si no coincide en tamaño, guardamos la imagen, puesto que no es la misma. Guardamos la imagen base que estamabos comparando
        save_baseimage = True

    if save_baseimage == True:
      cv2.imwrite(basefolder_path+"image"+str(num_image2write)+".jpg",baseImage)
      num_image2write = num_image2write +1
      save_baseimage = False

  print("Número de imagenes duplicadas en las búsquedas:")
  print(num_imag_dup)
  return num_imag_dup

In [0]:
BASE_FOLDER_noDup_ecooltra = BASE_FOLDER+"Dataset_noDup/ecooltra/"
BASE_FOLDER_noDup_acciona = BASE_FOLDER+"Dataset_noDup/acciona/"
BASE_FOLDER_noDup_yego = BASE_FOLDER+"Dataset_noDup/yego/"
BASE_FOLDER_noDup_muving = BASE_FOLDER+"Dataset_noDup/muving/"
BASE_FOLDER_noDup_blinkee = BASE_FOLDER+"Dataset_noDup/blinkee/"
BASE_FOLDER_noDup_motos = BASE_FOLDER+"Dataset_noDup/motos/"




In [0]:
#Test save paths

#baseImage = cv2.imread("/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000000.jpg")
#cv2.imwrite(BASE_FOLDER_noDup_ecooltra+"image"+str(num_image2write)+".jpg",baseImage)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


True

In [0]:

BuscarImagenesDuplicadas(files_ecooltra,BASE_FOLDER_noDup_ecooltra)

/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000000.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000001.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000002.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000003.png
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000004.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000005.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000006.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000007.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000008.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000009.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000010.jpeg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/ecooltra/00000011.jpg
/co

281

In [0]:
BuscarImagenesDuplicadas(files_acciona,BASE_FOLDER_noDup_acciona)

/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000000.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000001.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000002.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000003.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000004.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000005.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000006.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000007.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000008.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000009.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/acciona_motos/00000010.jpg
/content/drive/My Drive/Colab No

227

In [0]:
BuscarImagenesDuplicadas(files_yego,BASE_FOLDER_noDup_yego)

/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000000.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000001.png
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000002.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000003.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000004.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000005.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000006.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000007.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000008.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000009.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000010.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/yego_moto/00000

185

In [0]:
BuscarImagenesDuplicadas(files_muving,BASE_FOLDER_noDup_muving)

/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000000.jpg?quality=82&strip=all&w=1000
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000001.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000002.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000003.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000004.jpg?quality=82&strip=all
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000005.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000006.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000007.png
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000008.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000009.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/muving/00000010.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload

221

In [0]:
BuscarImagenesDuplicadas(files_blinkee,BASE_FOLDER_noDup_blinkee)

/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000000.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000001.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000002.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000003.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000004.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000005.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000006.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000007.JPG
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000008.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000009.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/Blinkee_city/00000010.jpeg
/content/drive/My Drive/Colab Notebooks/TF

73

In [0]:
BuscarImagenesDuplicadas(files_motos,BASE_FOLDER_noDup_motos)

/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000000.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000001.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000002.jpeg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000003.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000004.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000005.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000006.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000007.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000008.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000009.png
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000010.jpg
/content/drive/My Drive/Colab Notebooks/TFM/Dataset_donwload/motos/00000011.jpg
/content/drive/My Drive/Colab Notebooks

15